/**
 * @description       : 
 * @author            : joohyeon.jang@dkbmc.com
 * @group             : 
 * @last modified on  : 08-16-2023
 * @last modified by  : joohyeon.jang@dkbmc.com 
 * Modifications Log
 * Ver   Date         Author                    Modification
 * 1.0   08-16-2023   joohyeon.jang@dkbmc.com   Initial Version
**/
public with sharing class CjfwMDMManagementCommModalController {
    
}