/**
 * @description       : 
 * @author            : hyeeun.song@dkbmc.com
 * @group             : 
 * @last modified on  : 10-20-2023
 * @last modified by  : hyeeun.song@dkbmc.com
**/
public with sharing class CJFW_MDMExcelChooseColumnController {

    /* 속성부문 picklist */
    public static void getPropertyOptions() {
        
    }

    /* 속성군 picklist */
    public static void getAttributeOptions() {
        
    }

    /* 속성부문, 속성군, 타입에 따라 field값 다르게 도출하기 */
    public static void getDownloadField(String property, String attribute, String type, String searchWord) {

    }


}