/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-19-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
private class ExtraServiceCreateController_test {
    @testSetup
	static void setData() {
    }

    @isTest 
    static void itShould() {
        ExtraServiceCreateController.doInit();
    }
}