/**
 * @Class : IFN_LIF1002_OD003_NOF005.cls
 * @group Framework : 
 * @Author : 
 * @Date : 2023-08-11
 * @Version : 1.0
 * @Description : 
 * @Modified : 
 * ----------------------------------------------
 *  NO | Date       | Modifier       | Description
 * ----------------------------------------------
 *  1. | 2023.08.11 |  | 최초작성
 * */
@RestResource(urlMapping='/lif1002/od003/nof005')
global with sharing class IFN_LIF1002_OD003_NOF004 {
    public IFN_LIF1002_OD003_NOF005() {

    }
}